version: '3.5'

services:

  node_app: 
    container_name: toplaners_m_n
    build:
    image: #Aca va la imagen que vamos a subir?
    ports:
      - "3000:3000"
    enviroment: #Esto lo deberia poder cambiar el profe segun sus preferencias
      - NODE_ENV=development
      - DB_PROD_USERNAME=root
      - DB_PROD_PASSWORD= 
      - DB_PROD_DATABASE=universidad 
      - DB_PROD_HOST=localhost
      - DB_PROD_DIALECT=sqlite
    depends_on:
      - node_db
    #restart: always esto nose si dejarlo o no

  node_db:
    image: VARIABLE_DE_ENTORNO #La imagen de la base de datos que querramos
    #Aca irian las variables de entorno, que cambian de nombre segun el motor que usemos, asi que aca no podemos poner nada creo

    

  node_db2: #esto lo hizo pablen y no lo quiero borrar
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: always
    ports:
      - "3306:3306"

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database_name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: always
    ports:
      - "3307:3306"
